# Generated by Django 3.2.13 on 2022-10-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('happiness', models.IntegerField(default=70)),
                ('energy', models.IntegerField(default=70)),
                ('strength', models.IntegerField(default=1)),
                ('body_fat', models.IntegerField(default=10)),
                ('popularity', models.IntegerField(default=0)),
                ('gold', models.IntegerField(default=1000)),
                ('level', models.IntegerField(default=1)),
                ('feed', models.IntegerField(default=1)),
                ('meeting', models.IntegerField(default=0)),
                ('profile', models.ImageField(null=True, upload_to='home')),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_tower', models.CharField(max_length=20)),
                ('work_out', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Snacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
    ]
