# Generated by Django 3.2.13 on 2022-10-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challenge',
            name='condition',
            field=models.TextField(null=True),
        ),
    ]
